// unpack.h header file

#ifndef _DEFINED_4AFD424F_87A7_419e_832C_F8FC0AA1BC2E
 
#define _DEFINED_4AFD424F_87A7_419e_832C_F8FC0AA1BC2E
// Generated by GUIDGEN in Registry format


#if _MSC_VER > 1000  //
#pragma once                  
#endif    
//
#include "stdafx.h"
#include "cabextract.h"
                                                 
#ifdef __cplusplus  
extern "C" {                                     
#endif // 
                                                             
#ifdef _COMPILING_4AFD424F_87A7_419e_832C_F8FC0AA1BC2E

#define LIBSPEC __declspec(dllexport)                  
#else                                                    
#define LIBSPEC __declspec(dllimport)               
#endif // _COMPILING_4AFD424F-87A7-419e-832C-F8FC0AA1BC2E
 //
#define HAND struct file* 

LIBSPEC  HAND Cab_OpenArchive(const char * CabfileName);
LIBSPEC  BOOL Cab_CloseArchive(HAND CabFile);
LIBSPEC  BOOL  Cab_GetFirstFile(HAND &CabFile,const char * Directory,char *FileReturn);
LIBSPEC  BOOL  Cab_GetNextFile(HAND &CabFile,const char * Directory,char *FileReturn);


// ...                   
//#undef LIBSPEC   //
                                                                
#ifdef __cplusplus    
  }                                                   
#endif // __cplusplus  




#endif // _DEFINED_4AFD424F-87A7-419e-832C-F8FC0AA1BC2E

