// unpack.h header file

#ifndef _DEFINED_4AFD424F_87A7_419e_832C_F8FC0AA1BC2E
 
#define _DEFINED_4AFD424F_87A7_419e_832C_F8FC0AA1BC2E
// Generated by GUIDGEN in Registry format


#if _MSC_VER > 1000  //
#pragma once                  
#endif    
//
#include "stdafx.h"
#include "rar.hpp"
//#include "stdio.h"    
//#include "unzip.h"  
//#define NM 1204                                                     
#ifdef __cplusplus  
extern "C" {                                     
#endif // 
                                                             
#ifdef _COMPILING_4AFD424F_87A7_419e_832C_F8FC0AA1BC2E

#define LIBSPEC __declspec(dllexport)                  
#else                                                    
#define LIBSPEC __declspec(dllimport)               
#endif // _COMPILING_4AFD424F-87A7-419e-832C-F8FC0AA1BC2E
 //
#define HAND CommandData*
LIBSPEC CommandData Cmd;
LIBSPEC CmdExtract Extract;
LIBSPEC Archive ArcR;//(&Cmd);
LIBSPEC bool  success;
LIBSPEC bool  Repeat;
LIBSPEC  HAND Rar_OpenArchive(const char * ZipfileName,const char *Directory);
LIBSPEC  BOOL Rar_CloseArchive(HAND ZipFile);
LIBSPEC   BOOL Rar_GetFirstFile(HAND ZipFile, char *FileReturn);
LIBSPEC   BOOL Rar_GetNextFile(HAND ZipFile, char *FileReturn);
LIBSPEC   char  InRarFileName[256];

// ...                   
//#undef LIBSPEC   //
                                                                
#ifdef __cplusplus    
  }                                                   
#endif // __cplusplus  




#endif // _DEFINED_4AFD424F-87A7-419e-832C-F8FC0AA1BC2E

