/* Best viewed in -*- C -*- mode.
 *
 * $Id: resource.txt,v 1.3 2002/07/05 22:03:14 uid80112 Exp $
 *
 * Common ARJ/ARJSFX[V|JR]/REARJ message section. Splits into C header/source
 * files after being processed with MSGBIND.
 *
 * Translations contributed by:
 *
 *            German    -  Axel Dunkel       (c) 1995-1996
 *                         Alexander Bahlo   (c) 2000
 *            French    -  Frederic Taes     (c) 1995-1996
 *            Russian   -  Andrew Belov      (c) 1999-2002
 *
 * CAUTION: contains high-ASCII characters.
 */

/*
 * Far messages (subject to integrity checks in CHK_FMSG.C)
 */

#define  M_SDN_ADD_DESC                                       ""
#define  M_SDN_DIST_DESC                                       ""
#define  M_SDN_SECURITY_TEST                                        ""
#define  M_SDN_1                                                 ""
#define  M_SDN_2                                                 ""
#define  M_VERSION                                           ""
#define  M_REG_TYPE                                           ""
#define  M_ADDING                                                ""
#define  M_QUERY_ADD                                             "%s?"
#define  M_ALWAYS                                            ""
#define  M_ANSI_CP_ARCHIVE                                   ""
#define  M_NOT_OEM_CP_ARCHIVE                                    ""
#define  M_QUERY_APPEND                                      "%ld?"
#define  M_ARCHIVE_CREATED                                   "%s"
#define  M_MODIFIED                                          ",%s"
#define  M_ARCHIVE_SUFFIXES                                      ".ARJ.ZIP.PAK.ARC.RAR.J.UC2.LZH.ZOO"

#define  M_NO_DELETE_ARG                                       ""
#define  M_MISSING_FILENAME_ARG                              "%s"
#define  M_NO_FILE_GIVEN                                     ""
#define  M_NO_PWD_OPTION                                     ""
#define  M_ARGTABLE_OVERFLOW                                 ""
#define  M_INVALID_VOL_SIZE                                      ""
#define  M_PROTFILE_EXCEEDS                                      "%lu"
#define  M019                                                "ARJTEMP.$??"
#define  M_SELECTION_ERROR                                       ""
#define  M021                                                    ""
#define  M_DAMAGED_SEC_ARCHIVE                                   ""
#define  M_CANT_UPDATE_SEC                                       ""
#define  M_VALID_ENVELOPE                            ""
#define  M_SKIPPING_SEC                                       ""
#define  M_VALID_ARJSEC                                      "%s\n"
#define  M_VERIFYING_ARJSEC                          ""
#define  M_CANT_HANDLE_ARJSEC_V                                  "%d\n"
#define  M_CHAPTER_NUMBER                                        "%3d"
#define  M_CHAPTER_ERROR                                       "%d"
#define  M_NOT_A_CHAPTER_ARCH                                    ""
#define  M_ALREADY_CHAPTER_ARCH                                  ""
#define  M_TOO_MANY_CHAPTERS                                        "%d"
#define  M_CHAPTERS_OFF                                       ""
#define  M_CHAPTER                                               ""
#define  M_CHAPTERS_ON                                           ""
#define  M_NO_ARJSEC_KEY                                       ""
#define  M_INVALID_COMMAND                                   "%s\n\n"
#define  M_INVALID_COMMENT_HDR                               ""
#define  M_INVALID_MV_SEQ                                    ""
#define  M_INVALID_DATE_STRING                       "%s"
#define  M_INVALID_DATE                              ""
#define  M042                                                ""
#define  M_BAD_HEADER                                        ""
#define  M_INVALID_PARAM_STR                                        "%s"
#define  M_SIGNAL_FAILED                                     ""
#define  M_INVALID_SWITCH                            "%s"
#define  M_BAD_SYNTAX                                        ""
#define  M_BADTABLE                                          ","
#define  M_BADTABLE_G                                        ","
#define  M_BAK_EXT                                               ""
#define  M_BINARY_FILE                                           ""
#define  M_UXSPECIAL_FILE                                        ""
#define  M_CANT_QUERY_UXSPEC                                        ""
#define  M_BREAK_SIGNALED                            ""
#define  M_SIGTERM                               ""
#define  M_CANT_DELETE                                           "%s"
#define  M_CANT_TRUNCATE                                       "%s"
#define  M_CANTOPEN                            "%s"
#define  M_CANTREAD                                          ""
#define  M_CANTRENAME                                         "%s%s"
#define  M_CANT_RESET                                            "%s\n"
#define  M_DISK_FULL                                  ""
#define  M_QUERY_CASE_IGNORE                                        ""
#define  M_QUERY_COMMENT                                       "%s?"
#define  M_COMPRESSING                                           "%d"
#define  M_CONTINUED_NEXTVOL                                 ","
#define  M_QUERY_MORE                                        ""
#define  M_QUERY_NEXT_VOLUME                                 "%d"
#define  M_INSERT_DISKETTE                                   "%d\"%c\""
#define  M_CANT_COPY_TEMP                                        "%s%s"
#define  M_COPYING_TEMP                                       "%s%s\n"
#define  M_CRC_ERROR                                         ""
#define  M_OK                                                ""
#define  M_CRIT_ERROR                                        ""
#define  M_DRIVE                                             "%s%s%c\r\n"
#define  M_DEVICE                                            "%s%s%s\r\n"
#define  M_FOPEN                                             "%s%s\r\n"
#define  M_READING                                           ""
#define  M_WRITING                                           ""
#define  M_CURRENT_FILENAME                                      "%s\n"
#define  M_ENTER_CMD                                             ""
#define  M_DELETING_EMPTY_ARCH                                   "%s\n"
#define  M_QUERY_DELETE_N_FILES                                  "%ld"
#define  M_QUERY_DELETE                                       "%s?"
#define  M_DELETE_COUNT                                       "%ld"
#define  M_DELETING                                           "%s\n"
#define  M_FOREIGN_BINARY                                    ","
#define  M_DIRECTORY                                         ""

#define  M_CANT_MKDIR                          "%s\n"
#define  M_QUERY_CREATE_DIR                          "%s,"
#define  M_NOT_ENOUGH_SPACE_X                                "%ld"
#define  M_NOT_ENOUGH_SPACE                                      ","
#define  M_LOW_SPACE_WARNING                                        "%ld"
#define  M_NOT_ENOUGH_SPACE_V                                    ""
#define  M_EA_LIST                                               "%5u%5u%d.%03d%u"
#define  M_OWNER_LIST                                            "%s\n","","","%s\n"
#define  M_OWNER_ID                                              "%lu,%lu"
#define  M_UXLIST_FIFO                                           ""
#define  M_UXLIST_HLNK                                           "%s\n"
#define  M_UXLIST_LNK                                            "%s\n","","","%s\n"
#define  M_UXLIST_BLK                                            "%s","","","%s"
#define  M_UXLIST_CHR                                            "%s","","","%s"
#define  M_ENTER_NUM_MATCHES                                        "","","",","
#define  M_N_TICKS                                           "%6ld,","%6ld,","%6ld,","%6ld,"
#define  M_CANT_CNV_TO_DUAL_N                                    "","","","\"\""
#define  M_CANT_COMBINE_DUAL                                        "","","","\"\""
#define  M_PROT_SUFFIX                                           ""
#define  M_FILE_IS_GARBLED                                   ",",",",",",","
#define  M_COMMENT_TERMINATOR                                    ""
#define  M_SEEK_FAILED                                       "%ld","%ld","%ld","%ld"
#define  M_ARJ_SW                                            "ARJ_SW"
#define  M_EMPTY_COMMENT                                     ""
#define  M_FOUND_N_ERRORS                            "%5d","%5d","%5d","%d"
#define  M_ERROR_CODE                                            "%d%s","","","%d%s"
#define  M_EXIT_CMD                                          ""
#define  M_EXT_LIC                                               ""
#define  M_EXTRACTING_1_TO_2                                 "%s%s"
#define  M_AT_POSITION_N                                     "%ld"
#define  M_QUERY_EXTRACT                                       "%s?"
#define  M_EXTRACTING                                        "%s"
#define  M_EXTRACTING_CMT_TO_F                                   "%s\n"
#define  M_EXISTS                                            "%s,","%s,","%-12s,","%s,"
#define  M_FILE_IS_TOO_LARGE                                        "","","",""
#define  M_ARJFIXED_NAME                                       ""
#define  M_NOT_FOUND                                             ",",",","",","
#define  M_MATCHED                                               ",",",","",","
#define  M_NOT_MATCHED                                           ",",",","",","
#define  M_ENTER_PWD                                             "","","",""
#define  M_VERIFY_PWD                                            "","","",""
#define  M_PWD_MISMATCH                                       "","","",""
#define  M_GARBLING                                              "%s\n","%s\n","%s\n","%s\n"
#define  M_QUERY_GARBLE                                       "%s?","%s?","%s","%s?"
#define  M_WRONG_ENC_VERSION                                        "%d","","","%d"
#define  M_NONSTD_GARBLE                                     "","","",""
#define  M_NO_ARJCRYPT_ENTRY                                 "","","",""
#define  M_LOADING                                           "%s\n","","","%s...\n"
#define  M_ARJCRYPT_ERROR                                    "","","",""
#define  M_ENTER_COMMENT                                       "%d%s","%d%s","%d%s","%d%s.\nПустая"
#define  M_ENTER_SEARCH_STR                                      "%d","%d","%d","%d"
#define  M_GLOBAL                                            ""
#define  M_VLIST_HDR                                             ""
#define  M_VLIST_P1                                  ""
#define  M_LIST_P1                                   ""
#define  M_LIST_P2                                             "","","",""
//#define  M_LIST_P2                                               "","","",""
#define  M_LIST_P2_CHAP                                         ""
//#define  M_LIST_P2_CHAP                                           "","","",""
#define  M_HEADER_CRC_ERROR                                  ""
#define  M_NOTHING_TO_DO                                       "","","",""
#define  M_RESTART_INFO_NF                                       "","","",""
#define  M_CANT_RESTART_W_EAS                                    "","","",""
#define  M_INDEX_HDR                                         "","","",""
#define  M_NEXT_VOLUME_STATS                                        "%03d%01d%10ld%s\n"
#define  M_IS_SAME_OR_NEWER                                  "%s,","%s,","%-12s,","%s,"
#define  M_IS_SAME_OR_OLDER                                      "%s,","%s,","%-12s,","%s,"
#define  M_IS_SAME                                               "%s,","%s,","%-12s,","%s,"
#define  M_JT_UNUSABLE                                           "%s","%s","%s","%s"
#define  M_JO_UNUSABLE                                           "%s","%s","%s","%s"
#define  M_LABEL_FILE                                            "","","",""
#define  M_CANT_QUERY_LABEL                                      "","","",""
#define  M_SET_LABEL_ERROR                                   "","","",""
#define  M_REQUIRES_ARJ32                                        "","","",","
#define  M_ARCHIVE_CP_MISMATCH                                   "","","",""
#define  M_NAMES_LIMIT                                           "%ld%s\n","","","%ld,%s"
#define  M_HASH_MEM_LACK                             "%s\n","","","%s"
#define  M_SFX_CREATED                                           ""
#define  M_CREATING_ARCHIVE                                      "%s\n","%s\n","%s\n","%s\n"
#define  M151                                                    "","","",""
#define  M_CREATING_SFX                                       "%s\n"
#define  M_MARKING                                               "%s\n","%s\n","%s\n","%s\n"
#define  M_FOUND_N_OCCURENCES                                    "%4ld%s\n","%4ld%s\n","%4ld%s","%4ld%s>\n"
#define  M_REGISTRATION_INC                                      "%lu\n","","","%lu"
#define  M155                                                    "","","",""
#define  M_N_COMMENTS                                            "%6ld"
#define  M_TOTAL_STATS_LFN                                       "%6ld%10lu%10lu%u.%03u%s%6ld"
#define  M_TOTAL_STATS                                           "%6ld%10lu%10lu%u.%03u%s\n"
#define  M_N_FILES                                               "%6ld"
#define  M_VERBOSE_FOOTER                                        "%6ld%10lu,%10lu,%3d.%d%%\n"
#define  M_N_FILES_LFN                                           "%6ld%5ld"
#define  M_ENTER_NEW_FILENAME                                ""
#define  M_NO                                  ""
#define  M_NO_CHANGE                                             "%s","%s","%s","%s"
#define  M_CANT_FIND_DAMAGE                                      "%s","","","%s"
#define  M166                                                "","","",""
#define  M_CANT_FIND                                         "%s\n","%s\n","%s","%s\n"
#define  M_OUT_OF_NEAR_MEMORY                                ""
#define  M_OUT_OF_MEMORY                       ""
#define  M_NO_STR_ENTERED                                        "","","",""
#define  M_NOT_ARJ_ARCHIVE                                   "%s"
#define  M_NOT_EXISTS                                        "%s,"
#define  M_IS_NOT_SAME_DATE                                  "%s,"
#define  M_QUERY_CONTINUE                                        ""
#define  M_CURRENT_COMMENT                                       "%s:\n","%s:\n","%s:\n","%s:\n"
#define  M_ORDER_WILDCARD                                        "","","",""
#define  M_ORDER_CNT_MISMATCH                                    "","","",""
#define  M_CANT_ORDER_MV                                       ""
#define  M_QUERY_OVERWRITE                           ""
#define  M_MAXPATH_EXCEEDED                                   "%d%s\n"
#define  M_AT_POSITION                                           "%s%ld","%s%ld","%-12s%ld","%s,%ld"
#define  M_PRESS_ENTER                                       ""
#define  M_PROCESSING_ARCHIVE                        "%s\n"
#define  M_RESTORING_PROPERTIES                                  "%s","","","%s"
#define  M_PROTECT_BUG                                           "","","",""
#define  M_RECOVERY_ABORTED                                      "","","",","
#define  M_RECOVERY_CRC_DAMAGED                                  "","","",""
#define  M_RECOVERY_2CRC_DAMAGED                                 "%u","","","%u"
#define  M_SECTION_DAMAGED                                       "%u%u","","","%u%u\n"
#define  M_SECTION_RECOVERED                                        "%u","","","%u"
#define  M_NO_PROT_DATA                                       "","","",""
#define  M_PROT_RATIO                                            "%ld%ld.%d%%","","","%ld%ld.%d%%"
#define  M_ARJPROT_ENABLED                                       ""
#define  M_ARJPROT_DISABLED                                      ""
#define  M_ARJPROT_REJECTED                                      "","","",""
#define  M_QUIT                                      ""
#define  M_RANGE_EXCEEDED                                        "%s","","","%s"
#define  M_REGISTERED_TO                                     "%s]\n\n","%s]\n\n","%s]\n\n","%s]\n\n"
#define  M_QUERY_REMOVE_PATH                                        "%s?","%s?","%s","%s?"
#define  M_REMOVING_PATH                                       "%s\n","%s\n","%s\n","%s\n"
#define  M_QUERY_EXTRACT_RENAME                              ""
#define  M_FILES_REORDERED                                       "","","",""
#define  M_REPAIRED_FILE                                       "%s\n","","","%s\n"
#define  M_REPLACING                                             "","","",""
#define  M_OK_TO_RETRY                                       "","","",","
#define  M_CANT_FIND_RST_FILE                                    "%s","%s","%s","%s"
#define  M_EXE_EXT                                           ""
#define  M_QUERY_SCANNED_ENOUGH                                  ""
#define  M205                                                    ""
#define  M206                                                    "%s","%s","%s","%s"
#define  M_ENTER_CMD_EXIT                                        "","","",","
#define  M_N_BYTES													"%10ld,"
#define  M_SKIP                                              ""
#define  M_SKIPPED                                   "%s\n"
#define  M_CHAPTER_SFX_CREATION                                  "","","",""
#define  M_INVALID_SFX_SW_USE                                    ""
#define  M_NO_GARBLE_IN_SFXJR                                    "","","",""
#define  M_DOS_MODE_SFXJR                                            "\"\"","","",""
#define  M_NO_LABELS_IN_SFX                                      "","","",""
#define  M_INVALID_METHOD_SFX                                    "","","",""
#define  M_MULTIVOLUME_SFXJR                                        ""
#define  M_SEARCHING                                             "%-60s","%-60s","%-60s","%-60s"
#define  M_STORING                                               "","","",""
#define  M_EXT_ARJ                                               ".ARJ"
#define  M_COMMAND                                               ""
#define  M_TESTING                                           "%s","%s","%-12s","%s"
#define  M_TEXT_FILE                                             "","","",""
#define  M_REARCHIVING                                           "%s","%s","%s","%s"
#define  M_FINAL_TIMING                                      "%6ld","%6ld","%6ld","%6ld\n"
#define  M_UNCOMPRESSING                                       "%d","%d","%d","%d"
#define  M_UNGARBLING                                            "%s\n","","","%s\n"
#define  M_UNKNOWN_METHOD                                    "%d,","%d,","%d,","%d,"
#define  M_UNKNOWN_FILE_TYPE                                 "%d,","%d,","%d,","%d,"
#define  M_UNKNOWN_VERSION                                   "%d,","%d,","%d,","%d,"
#define  M_UNMARKING                                             "%s\n","%s\n","%s\n","%s\n"
#define  M_UNSTORING                                             "","","",""
#define  M_QUERY_UPDATE                                       "%s?","%s?","%s","%s?"
#define  M_UPDATING                                              "","","",""
#define  M_UPDATING_ARCHIVE                                      "%s\n","%s\n","%s\n","%s\n"
#define  M_MV_UPDATE_REQ_SW                                      "","","",""
#define  M_USING_ENV_VAR                                       "%s=%s\n","%s=%s\n","%s%s\n","%s=%s\n"
#define  M_WORKING                                               "","","",","
#define  M_ARJ_VS_DISK                                       "ARJ %10ld %s, DISK %10ld %s\n"
#define  M_BY_DATE                                               "","","",""
#define  M_BY_SIZE                                               "","","",""
#define  M_BY_DATA                                               "","","",""
#define  M_TO                                                    "%s","","%s","%s"
#define  M_YES                                 ""
#define  M_REPLIES_HELP                              ",,"
#define  M_ALL_REPLIES_HELP                                  ",,,,,,"
#define  M_REPLIES                                           ""
#define  M_ARJ_BANNER                                            "%s%s,,%s\n\n"

/*
 * OS-specific messages
 */

#define  M_REQUIRES_WIN95                                         ",","",",",","
#define  M_TEXTMODE_LFN_SFXJR                                     "","","",""
//#define  M_TEXTMODE_LFN_SFXJR                                "","","",""
#define  M_LFN_ENABLED                                            "","","",""
#define  M_EA_ENABLED                                              "","","",""
#define  M_LISTING_XMS_ERROR                                         "%s","","%s","%s"
#define  M_OS_DEPENDENT                                        "%s","","%s","%s"
#define  M_EA_STATS_STG                                        "%u"
#define  M_CANT_SET_EA                                         ",","","",","
#define  M_UXSPECIAL_UNSUPP                                    ",","","",","
#define  M_CANT_SET_UXSPECIAL                                    ",","","",","
#define  M_UXSPECIAL_FIFO                                        "","","",""
#define  M_UXSPECIAL_HLNK                                        "","","",""
#define  M_UXSPECIAL_LNK                                         "","","",""
#define  M_UXSPECIAL_BLK                                         "","","",""
#define  M_UXSPECIAL_CHR                                         "","","",""
#define  M_NO_LINKING                                            ",","","",","
#define  M_FOREIGN_SYSTEM                                        ",","","",","
#define  M_CANT_CHOWN                                            ",","","",","
#define  M_UXSPEC_SUPPRESSED                                     ",","","",""

/*
 * Bindings
 */

#define  M_ARJ_BINDING                                                  ""

/*
 * Parameter table
 */

#define  M_CMD_TABLE                                             "ABCDEFGIJKLMNOPQRSTUVWXYZ"
#define  M_SW_TABLE                                              "JHABCDEFGIKLMNOPQRSTUVWXYZ?!$+#&*@@2"
#define  M_JSW_TABLE                                             "JABCDEFGHIKLMNOPQRSTUVWXYZ#$"
#define  M_HSW_TABLE                                             "HABCDEFGIKLMNOPQRSTUVWXYZ#*$2"
#define  M_OS2SW_TABLE                                           "2ACDEFHKLOPSX"
#define  M_ADD_COMMANDS                                       "AFJMU"
#define  M_UPDATE_COMMANDS                                       "AJMU"
#define  M_MODIFY_COMMANDS                                       "ACDFGJKMNORUYZ"
#define  M_DIR_COMMANDS                                       "ABEFJMUX+"
#define  M_JYSW_TABLE                                            "ACDKNORSVY"
#define  M_SW_PARAMS                                             "00150113060040010031300000000010200"
#define  M_JSW_PARAMS                                            "0130111100001010020301000040"
#define  M_HSW_PARAMS                                            "00000140090001020000010002200"
#define  M_OS2SW_PARAMS                                       "0001000101000"

/*
 * Format variables
 */

#define  M_CHAPTER_LIST_FMT                                      "<<< %03d - %03d >>>\n"
#define  M_LIST_NUM_FMT                                      "%03ld) "
#define  M_REV_OS_FMT                                "%3d %-8s "
#define  M_PATH_LIST_FMT                                       " %-7s %-32s %s"
#define  M_VERBOSE_LIST_LINE                                          "%10ld %10ld %u.%03u%c%s  %3d %3d %4s%c%c"
//#define  M_VERBOSE_LIST_LINE                                            "%10ld %10ld %u.%03u%c%s  %3d %3d %14s"
#define  M_STD_LIST_LINE                                       "%10ld %10ld %u.%03u%c%s %08lX %4s%c%c%c%u%c%c%c"
//#define  M_STD_LIST_LINE                                         "%10ld %10ld %u.%03u%c%s %14s %c%c%u%c%c"
#define  M_ATIME_FMT                                             "                                   DTA  %c%s\n"
#define  M_CTIME_FMT                                             "                                   DTC  %c%s\n"
#define  M_IDX_VOLUME_HEADER                                        "%s %10ld %s\n"
#define  M_FILENAME_FORM                             "%s\n"
#define  M_EMPTY_ATTR                                          "    "
//#define  M_EMPTY_ATTR                                            "              "
#define  M_LIST_SEPARATOR                                      "------------ ---------- ---------- ----- ----------------- -------- -----------\n"
//#define  M_LIST_SEPARATOR                                        "------------ ---------- ---------- ----- ----------------- -------------- -----\n"
#define  M_BRIEF_LIST_SEPARATOR                      "------------ ---------- ---------- -----\n"
#define  M_FINAL_FOOTER                                       "----------------------------------------------------------\n"
#define  M_LONG_NAME_FMT                                     "%-12s \n             "
#define  M_SHORT_NAME_FMT                            "%-12s "
#define  M_IDXFMT_NP                                             "%s\n"
#define  M_IDXFMT_SHORT                                       "%s %s\n"
#define  M_IDXFMT_LONG                                           "%s \"%s\"\n"
#define  M_CHAPMARK_FORMAT                                       "<<<%03d>>>"
#define  M_MARK_LLINE                                            "----->\n"
#define  M_FSTAT_1                                               "          \n"
#define  M_FSTAT_2                                               "%3d.%d%%    "
#define  M_IDX_FIELD                                             "%s %10ld %10ld %u.%03u %s\n"
#define  M_NO_RATIO                                              "  0.0%%\n"
#define  M_LIST_FORM                                             "%s  "
#define  M_ARJDISP_INVOCATION                        "%s %s %s %ld %ld %ld %c"
#define  M_VOLUME_BUG                                            "?S %s\n"
#define  M_AUTOPROT_DAMAGE                                       "?D %s\n"

/*
 * XMS procedures
 */

#define  M_XMS_READ                                                "","","",""
#define  M_XMS_WRITE                                               "","","",""
#define  M_XMS_INIT                                                "","","",""

/*
 * Miscellaneous filenames
 */

#define  M_ARJCRYPT_COM                                       "ARJCRYPT.COM"
//#define  M_ARJCRYPT_COM                                        ""
//#define  M_ARJCRYPT_COM                                          ""
#define  M_WIN95_LFN_TRANSL                                        "%03d"
//#define  M_WIN95_LFN_TRANSL                                          "%03d"
#define  M_ARJ_CFG                                               "arj.cfg"
/*
 * Encoding messages (displayed only when debug switches are present)
 */

#define  M_LARGE_DICTIONARY                                      "","","",""
#define  M_LARGE_GSIZE                                           "","","",""
#define  M_PUTBIT_SIZE_ERROR                                        "","","",""

/*
 * DOS messages
 */

#define  M260                                                 "","","",""
#define  M261                                                 "","","",""
#define  M262                                                 "","","",""
#define  M263                                                 "","","",""
#define  M264                                                 "","","",""
#define  M265                                                 "","","",""
#define  M266                                                 "","","",""
#define  M267                                                 "","","",""
#define  M268                                                 "","","",""
#define  M269                                                 "","","",""
#define  M270                                                 "","","",""
#define  M271                                                 "","","",""
#define  M272                                                 "","","",""
#define  M273                                                     "","","",""
#define  M274                                                     "","","",""
#define  M275                                                     "","","",""
#define  M276                                                     "","","",""
#define  M277                                                     "","","",""
#define  M278                                                 "","","",""

/*
 * Debug data - pops up only when special debug switches are encountered
 */

#define  M_PRECOMP_STAT                                       "%d,%d,%d,%d,%d"
#define  M_MEMSTATS                                              "%5u%d,%6lu%d,%5u","","%5u%d,%6lu%d,%5u","%5u%d,%6lu%d,%5u"
#define  M_XLIST_BLOCKS                                       "%d\n","","","%d\n"
#define  M_HASH_MATCHES                                       "%ld,%ld","","%ld%ld","%ld%ld"
#define  M_SEARCH_FLAG                                           "%d\n","","","%d\n"
#define  M_BUFSIZ                                                "%u","","%u","%u"
#define  M_HDF_FIX                                               "","","",""
#define  M_BRIEF_MEMSTATS                                        "%5u,%5u,%5u\n"
#define  M_AVAIL_SPACE                                           "%lu","","%lu","%lu"
#define  M_TOKEN                                                 "%s\n"
#define  M_BAD_HEAP                                              ""
#define  M_ARCH_SIZE                                             "%10ld%s\n"
#define  M_ENCRYPT_VALUE                                       "%d\n"
#define  M_EXITING_PROGRAM                                       ""
#define  M_HERE_TWICE                                            "","","",""
#define  M_DECODE_CRIT_ERROR                         "","","",""
#define  M_DECODE_EOF                                "","","",""

/*
 *
 * ARJCRYPT section
 *
 */

#define  M_ARJCRYPT_BANNER                                       ","

/*
 *
 * ARJSFXV dedicated section
 *
 */

//#define  M_WRONG_ENC_VERSION                                      "","","",""
#define  M_ARJSFX_BANNER                                          "%s%s,%s\n","","%s%s,%s\n","%s%s,%s\n"
//#define  M_SW_TABLE                                               ""
//#define  M_SW_PARAMS                                              ""
//#define  M_JYSW_TABLE                                             ""
//#define  M_ARCHIVE_SUFFIXES                                       ""
//#define  M_DAMAGED_SEC_ARCHIVE                               "","","",""
#define  M_DAMAGED_SFX                                       "","","",","
#define  M_EXTR_CMD_QUERY                                         "\"%s\"","","\"%s\"","\"%s\""
#define  M_EXECUTING_CMD                                          "\"%s\"","","\"%s\"","\"%s\""
//#define  M_ENTER_PWD                                              "","","",""
//#define  M_VLIST_HDR                                              "","","",""
//#define  M_REQUIRES_WIN95                                     ",","",",",","
//#define  M_NAMES_LIMIT                                      "%ld%s\n","","%ld%s\n","%ld,%s"
//#define  M_N_COMMENTS                                             "%6ld","","%6ld","%6ld\n"
//#define  M_TOTAL_STATS                                            "%6ld%10ld%10ld%u.%03u%s%s\n","","%6ld%10ld%10ld%u.%03u%s%s\n","%3ld%9ld%10ld%u.%03u%s%s\n"
//#define  M_N_FILES                                                "%6ld","","%6ld","%3d"
//#define  M_NOT_ENOUGH_SPACE                                       "\"%s\",","","","\"%s\""
#define  M_CONTINUE_EXTRACTION                               ""
#define  M_QUERY_DEST_DIR                                    "%s"
#define  M_ENTER_INSTALL_DIR                                 "","","",""
#define  M_SFX_USAGE                                              "","","",""
#define  M_SFX_COMMANDS                                           @hsfxv_en.txt, "",,

/*
 * Debug data - pops up only when special debug switches are encountered
 */

//#define  M_MEMSTATS                                               "%5u,%6lu","","%5u,%6lu","%5u,%6lu"

/*
 *
 * ARJSFX dedicated section. Here and below, in ARJSFXJR, some messages
 * are very cryptic. However, lack of space makes this necessary.
 *
 */

//#define  M_ARJSFX_BANNER                                            "%s","","%s","%s,"
//#define  M_SW_TABLE                                                 ""
//#define  M_ARCHIVE_CREATED                                          "%s\n","","","%s\n"
//#define  M_NO_PWD_OPTION                                            "","","",""
//#define  M_ARGTABLE_OVERFLOW                                 "","","",""
//#define  M_VALID_ARJSEC                                             "%s\n","%s\n","%s\n","\"\"%s\n"
//#define  M_BAD_HEADER                                         "","","",""
//#define  M_INVALID_SWITCH                                           "%c\n\n","","%c\n\n","%c"
//#define  M_BADTABLE                                           "","","",""
//#define  M_BADTABLE_G                                               "","","",""
//#define  M_CANTREAD                                           "","","",""
//#define  M_DISK_FULL                                          "","","",","
//#define  M_CRC_ERROR                                                "","","",""
//#define  M_OK                                                       ""
//#define  M_FOREIGN_BINARY                                           ",",",",",",","
//#define  M_FILE_IS_GARBLED                                          ",",",",",",","
//#define  M_EXTR_CMD_QUERY                                           "\"%s\"","","\"%s\"","\"%s\""
#define  M_EXECUTING_CMD                                            "\"%s\"","","\"%s\"","\"%s\""
//#define  M_EXTRACTING_1_TO_2                                        "%-12s%s","%-12s%s","%-12s%-12s","%-12s%s"
//#define  M_EXTRACTING                                               "%s,","%s,","%-12s,","%s,"
//#define  M_EXISTS                                                   "%-12s,","%-12s,","%-12s,","%-12s,"
//#define  M_VLIST_HDR                                                "","","",""
//#define  M_LIST_P2                                                    "","","",""
//#define  M_LIST_P2                                                      "","","",""
//#define  M_HEADER_CRC_ERROR                                         "","","",""
//#define  M_IS_SAME_OR_NEWER                                         "%-12s,","%-12s,","%-12s,","%-12s,"
//#define  M_TOTAL_STATS                                              "%5d%10ld%10ld%u.%03u\n","","","%3d%9ld%10ld%u.%03u\n"
//#define  M_N_FILES                                                  "%5d","","","%3d"
//#define  M_NOT_EXISTS                                               "%-12s,","%-12s,","%-12s,","%-12s,"
#define  M_RAW_INPUT_REJECTED                                       "","","",""
//#define  M_TESTING                                                  "%s,","%s,","%-12s,","%s,"
//#define  M_UNCOMPRESSING                                            "","","",""
//#define  M_UNSTORING                                                "","","",""
//#define  M_SFX_USAGE                                                "","","",""
//#define  M_SFX_COMMANDS                                             ","",,"
//#define  M_STD_LIST_LINE                                              "%10ld%10ld%u.%03u%s%08lX%4s%c%c%u%c\n"
//#define  M_STD_LIST_LINE                                                "%10ld%10ld%u.%03u%s%14s%c%u%c\n"
//#define  M_LIST_SEPARATOR                                             ""
//#define  M_LIST_SEPARATOR                                               ""
//#define  M_LONG_NAME_FMT                                            "%-12s\n"
#define  M_VERBOSE_NAME_FMT                                         "%-12s\n"

/*
 *
 * ARJSFXJR dedicated section. Everything must be as short as possible.
 *
 */

//#define  M_ARJSFX_BANNER                                              "","","",","
//#define  M_HEADER_CRC_ERROR                                           "","","",""
#define  M_SFXJR_TICKER                                               ""
#define  M_VD_SPACE                                                   ""
//#define  M_SKIPPED                                                    ""
#define  M_FILE_EXISTS                                                "","","",""
#define  M_CANTOPEN_F                                                 "","","",","
//#define  M_EXTRACTING                                                 "","","",""
//#define  M_OK                                                         ""
//#define  M_CRC_ERROR                                                  "","","",""
//#define  M_INVALID_SWITCH                                             "","","",""
//#define  M_CANTOPEN                                                   "","","",""
//#define  M_PROCESSING_ARCHIVE                                         "","","",""
#define  M_EXTRACTED                                                  "","","",""
#define  M_FILES                                                      "","","",""
//#define  M_BREAK_SIGNALED                                             "","","",""
#define  M_FOUND_ERRORS                                               "","","",""

/*
 *
 * REARJ dedicated section.
 *
 */

#define  M_NO_INTEGRITY_PATTERN                                       "","","",""
#define  M_INTEGRITY_VIOLATED                                         "","","",""
#define  M_INTEGRITY_OK                                               "","","",""
#define  M_REARJ_BANNER                                               ",%s\n","",",%s\n",",,%s\n"
#define  M_REARJ_COMMANDS                                             @hrej_en.txt, "",,
#define  M_REARJ_RCODES                                               @hrejc_en.txt, "",,
//#define  M_CANTREAD                                                   "","","",""
//#define  M_REPLIES_HELP                                               "","",",",","
#define  M_CANT_CLEAR_ATTRS                                           "%s","","%s","%s"
#define  M_MAXDIR_EXCEEDED                                            "%s","","%s","%s"
#define  M_CANT_RMDIR                                                 "%s","","%s","%s"
#define  M_CANT_UNLINK                                                "%s","","%s","%s"
#define  M_CANT_WRITE_LOG                                             "","","",""
#define  M_GETCWD_FAILED                                              ""
#define  M_PATH_NOT_FOUND                                             "%s\n","","%s\n","%s\n"
#define  M_CANT_CHDIR                                                 "%s","","%s","%s"
#define  M_SKIP_CANT_FIND                                             "%s.","","%s.","%s"
#define  M_SKIP_UNKNOWN_TYPE                                          "%s.","","%s.","%s"
#define  M_SKIP_TGT_EXISTS                                            "%s.","","%s.","%s"
#define  M_SKIP_REPACK                                                "%s.","","%s.","%s"
#define  M_CONVERTING_ARCHIVE                                         "%s%s%s\n","","%s%s%s\n","%s%s%s\n"
#define  M_QUERY_CONVERT                                              "","","",""
#define  M_SKIPPING                                                   "%s.\n\n","","%s.\n\n","%s"
#define  M_EXECUTING_PRE                                              "%s\n","","%s\n","%s\n"
#define  M_EXECUTING                                                  "%s\n","","%s\n","%s\n"
#define  M_SKIP_EXE_MISSING                                           "%s.","","%s.","%s"
#define  M_SKIP_UNPACK_ERR                                            "%s.%d","","%s.%d","%s%d"
#define  M_SKIP_UNSUPP_DIR                                            "%s.","","%s.","%s"
#define  M_SKIP_NO_FILES                                              "%s.","","%s.","%s"
#define  M_EXECUTING_CNT                                              "%s\n","","%s\n","%s\n"
#define  M_EXECUTING_EXTR                                             "%s\n","","%s\n","%s\n"
#define  M_SKIP_V_EXE_MISSING                                         "%s.","","%s.","%s"
#define  M_SKIP_V_ERR                                                 "%s.%d","","%s.%d","%s%d"
#define  M_SKIP_REARJ_MISSING                                         "%s.","","%s.","%s"
#define  M_SKIP_REARJ_FAILED                                          "%s.%d","","%s.%d","%s%d"
#define  M_SKIP_CANT_RENAME                                           "%s.%s.\n\n","","%s.%s.\n\n","%s%s.\n\n"
#define  M_BACKED_UP                                                  "%s%s.\n","","%s%s","%s%s.\n"
#define  M_SKIP_P_EXE_MISSING                                         "%s.","","%s.","%s"
#define  M_SKIP_PACK_ERR                                              "%s.%d","","%s.%d","%s%d"
#define  M_SKIP_NOT_PACKED                                            "%s.","","%s.","%s"
#define  M_SKIP_LARGER                                                "%s.","","%s.","%s"
#define  M_VERIFYING_SIZE                                             "%d%ld.\n","","%d%ld.\n","%d%ld"
#define  M_FOUND_SIZE                                                 "%d%ld.\n","","%d%ld","%d,%ld.\n"
#define  M_SKIP_COUNT_MISMATCH                                        "%s.","","%s.","%s"
#define  M_SKIP_SIZE_MISMATCH                                         "%s.","","%s.","%s"
#define  M_SIZE_VERIFIED                                              "","","",""
#define  M_SKIP_DISK_FULL                                             "%s.","","%s.","%s"
#define  M_DELETING_2                                                 "%s\n","","%s\n","%s\n"
#define  M_RENAMING                                                   "%s%s\n","","%s%s","%s%s"
#define  M_CANT_COPY                                                  "%s%s","","%s%s","%s%s"
#define  M_OLD_SIZE                                                   "%10ld\n","","%10ld\n","%10ld\n"
#define  M_NEW_SIZE                                                   "%10ld\n","","%10ld\n","%10ld\n"
#define  M_SAVINGS_SIZE                                               "%10ld\n","","%10ld\n","%10ld\n"
#define  M_LISTFILE_MISSING                                           "","","",""
#define  M_CANT_FIND_CONFIG                                           "%s","","%s","%s,"
#define  M_USING_CONFIG                                               "%s\n\n","","%s\n\n","%s\n\n"
#define  M_NO_ANTIVIRUS_PATH                                          "","","",""
#define  M_IGNORED_FOR_COMP                                           ",","","",""
#define  M_INVALID_SUFFIX                                             "%s","","%s","%s"
#define  M_MISSING_PACK_CMD                                           "%s","","%s","%s"
#define  M_NO_PACK_STRFORM                                            "%%s%s","","%%s%s","\"%%s\"%s"
#define  M_INVALID_PACK_CMD                                           "%s","","%s","%s"
#define  M_MISSING_UNPACK_CMD                                         "%s","","%s","%s"
#define  M_NO_UNPACK_STRFORM                                          "%%s%s","","%%s%s","\"%%s\"%s"
#define  M_INVALID_UNPACK_CMD                                         "%s","","","%s"
#define  M_MISSING_OPTIONS                                            "%s","","%s","%s"
//#define  M_BREAK_SIGNALED                                             "","","",""
//#define  M_REGISTERED_TO                                              "%s]\n\n","","%s]\n\n","%s]\n\n"
//#define  M_SIGNAL_FAILED                                              "","","",""
#define  M_USING_REARJ_SW                                             "%s\n","","%s\n","%s\n"
#define  M_PROGRAM_CRC_ERROR                                          "","","",""
#define  M_YD_CMD_CONFLICT                                            "","","",""
#define  M_LY_CMD                                                     "","","",""
#define  M_NO_V_CMD                                                   "%s.","","%s","%s"
#define  M_INVALID_F_SUFFIX                                           "%s","","%s","%s"
#define  M_INVALID_T_SUFFIX                                           "%s","","%s","%s"
#define  M_SIMULATION_MODE                                            ",,","",",",","
#define  M_NO_LISTFILE                                                "","","",""
#define  M_NO_FILES_INT                                               "","","",""
#define  M_NO_FILES                                                   "","","",""
#define  M_CWD_MUST_BE_EMPTY                                          "","","",""
#define  M_WORK_DIR_NOT_EMPTY                                         "%s","","%s","%s"
#define  M_CANT_GET_FULL_PATH                                         "","","",""
#define  M_OK_TO_QUIT                                                 "","","",""
#define  M_QUITTING                                                   "","","",""
#define  M_TOTAL_SECONDS                                              "%10ld\n","","%10ld\n","%10ld"
#define  M_TOTAL_CONVERTED                                            "%8d\n","","%8d\n","%10d\n"
#define  M_TOTAL_SKIPPED                                              "%10d\n","","%10d\n","%10d\n"
#define  M_LOGENTRY_MARKER                                             "%02d:%02d:%02d%3s%s\n"
#define  M_LOGENTRY_HEADER                                             "%02d:%02d:%02d%3s","","%02d:%02d:%02d%3s","%02d:%02d:%02d%3s"
#define  M_LOGENTRY_SKIP                                               "%02d:%02d:%02d%3s%10d%s\n","","%02d:%02d:%02d%3s%10d%s\n","%02d:%02d:%02d%3s%10d%s\n"
#define  M_LOGENTRY_CONV                                               "%02d:%02d:%02d%3s%10ld%10ld%10ld%s\n"
#define  M_LOGENTRY_FOOTER                                             "%02d:%02d:%02d%3s%10ld%10ld%10ld%10ld"

/*
 *
 * REGISTER dedicated section.
 *
 */

//#define  M_CANTOPEN                                           "%s","%s","%s","%s"
//#define  M_CANTREAD                                           "%s","","%s","%s"
#define  M_CANT_SEEK                                          "%s","","%s","%s,"
#define  M_CANT_WRITE                                         "%s","","%s","%s"
#define  M_REG_TOTALS                                         "%d","","%d","%d"
#define  M_REG_FAILED                                         "","","",""
#define  M_REGISTER_BANNER                                    ",","",",",",,,"
#define  M_PATCH_NOT_FOUND                                    "","","",""
#define  M_REGISTER_STAMPED                                   "%s","","%s","%s"
#define  M_VERIFY_REGISTRATION                                "%s.\n","","%s",",%s.\n"
#define  M_MISSING_REG_FILE                                   "","","",""
#define  M_REGISTER_HELP                                      @hreg_en.txt, "",,
#define  M_IMPROPER_REG_FMT                                   "","","",","

/*
 *
 * ARJ$DISP dedicated section.
 *
 */

#define  M_ARJDISP_COPYRIGHT                                           ",","",",",",,,"
#define  M_ARJDISP_DISTRIBUTION                                        "","","",""
#define  M_ARJDISP_LICENSE                                             "","","",""
//#define  M_PROCESSING_ARCHIVE                                          "%s","","%s","%s"
#define  M_FINISHED_PROCESSING                                         "%s","","%s","%s"
#define  M_ARJDISP_INFO                                                @hadi_en.txt, "","",
#define  M_PRESS_ANY_KEY                                               ""
#define  M_EXTRACTING_FILE                                             "%s","","%s","%s"
#define  M_PROCESSING_FILE                                             "%s","","%s","%s"
#define  M_TESTING_FILE                                                "%s","","%s","%s"
#define  M_ADDING_FILE                                                 "%s","","%s","%s"
#define  M_ARJDISP_CTR_START                                           "","","","%%"
#define  M_ARJDISP_CTR                                                 "%3d","","%d","%3d%%"
#define  M_ARJDISP_BANNER                                              "","","",""

/*
 *
 * SFX_STUB dedicated section.
 *
 */

#define  M_SFXSTUB_BANNER                                         ","
#define  M_SFXSTUB_BLURB_1                                        "","","",""
#define  M_SFXSTUB_BLURB_2                                        "","","",""
